name: in_app_purchase_service
description: A service for managing in-app purchases in a Flutter app.
version: 1.0.0

environment:
  sdk: '>=2.18.6 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
dependencies:
  in_app_purchase: ^3.1.1
